// crypto-v4 refinements, evaluated against saved transcripts and challenge cases.
// Keep old prompt versions identifiable; these rules cannot repair cached output.
export const MARKET_PROMPT_GUIDANCE = `
MARKET-OUTLOOK DISAMBIGUATION (these rules refine the scoring rubric above):
1. Measure expected asset price/market direction, not enthusiasm for technology, developer tools, security, adoption goals, NFTs or a sponsor. A video can be relevant with every score null. Ecosystem praise alone is NOT a market outlook. "Bullish from a tech perspective" alone means no market score.
2. A price opinion takes priority over unrelated ecosystem praise: "I like its developers but expect the token to fall" is bearish, not neutral. A preference for SOL over ETH does not by itself predict an absolute ETH decline. Preserve genuinely conflicting price horizons in the summary; do not mix technology sentiment into price sentiment.
3. Attribute views carefully in interviews and panels. Guest or quoted third-party views are not automatically the channel creator's views. Only use them for the creator's scores/calls/actions if the creator explicitly endorses them. A question, polite acknowledgement or silence is not endorsement. If speaker identity or endorsement cannot be established, abstain from attribution and explain the uncertainty in the summary. Do not guess from subject knowledge.
4. An action needs an actual recommendation, present position or current plan. Generic discussion of "knowing when to take profits" is not a take_profits action. A retrospective "we sold last October" is not a new sell action today. Include a current reaffirmation ("we remain risk off") only with evidence of that current stance. A scheduled future or conditional action must be marked conditional, with its timing/condition in the quote.
5. Calls require an endorsed expectation of future market-price direction. Technology adoption, future inflows, relative outperformance and a description of an existing trend alone are not absolute-price forecasts. Include negation, the named asset or an unambiguous adjacent asset reference, and any governing if/when clause in the evidence range. "If Bitcoin flips bullish, buy" is conditional even when the instruction is emphatic.
6. Humor, irony and sarcasm are common. Read the surrounding setup, punchline, quotation, immediate correction and later reaffirmation before treating emphatic language as a sincere market view. "Sell everything, Bitcoin is dead... just kidding" is neither a bearish call nor a sell action. "Yeah, because prices only go up" can be ironic; do not mechanically invert it into a bearish forecast either. Catchphrases, mock panic, parody and hyperbole alone are not actionable views. When the literal meaning is contradicted or sincerity is uncertain, omit the ambiguous score/call/action, explain the ambiguity in the summary and lower confidence. An independently explicit, sincere view elsewhere can still support a score/call/action. Include the correction/negation in evidence, never cherry-pick the setup. Transcripts lack tone of voice; do not invent vocal cues or assume every extreme statement is a joke.
7. Confidence measures certainty that the extraction faithfully represents the source, NOT the probability a prediction will come true. Ambiguous speakers, translation errors and conflicting context reduce extraction confidence. Never repair caption spelling inside evidence.

Boundary examples (illustrative only; never use these as source evidence):
- "Bitcoin has strong security; this tutorial shows how wallets work." => relevant, all scores null, no calls/actions.
- "Solana development is exciting, but I expect SOL to fall to $30." => bearish SOL/overall; bearish SOL call; no inferred sell action.
- "Knowing when to take profits matters." => no take_profits action.
- "We sold last year. If BTC breaks resistance, we will buy." => no new sell action; conditional BTC buy.
- "Guest: I expect Bitcoin to rise. Host: What makes you think that?" => no creator BTC forecast or score.
- "Sell all your Bitcoin! We're going to zero! Just kidding. I have no directional view." => no market score, call or action.
- "Bitcoin only goes up, obviously. Yeah, right. I don't know what happens next." => no bullish or bearish call; no inferred buy/sell.
Before returning JSON, check every score/call/action against these distinctions. Omit unsupported items rather than filling fields for completeness.`;
